/**
 * Knowledge Loader — loads structured knowledge packs into KIOKU memory
 * Used for Agent O's deep expertise in hair art, art history, music, fashion
 */
import { pool } from "./storage";

interface KnowledgeChunk {
  domain: string;
  category: string;
  title: string;
  content: string;
  importance: number;
  tags: string[];
}

/** Load a knowledge pack into memory for a specific user */
export async function loadKnowledgePack(userId: number, agentId: number, chunks: KnowledgeChunk[]): Promise<number> {
  let loaded = 0;
  for (const chunk of chunks) {
    try {
      await pool.query(
        `INSERT INTO memories (user_id, agent_id, content, type, importance, namespace, created_at)
         VALUES ($1, $2, $3, 'semantic', $4, $5, $6)`,
        [userId, agentId, `[${chunk.domain}/${chunk.category}] ${chunk.title}: ${chunk.content}`, chunk.importance, `_knowledge_${chunk.domain}`, Date.now()]
      );
      loaded++;
    } catch { /* skip duplicates */ }
  }
  // Update domain chunk count
  await pool.query(
    `INSERT INTO knowledge_domains (user_id, name, slug, description, category, chunk_count, status, created_at, updated_at)
     VALUES ($1, $2, $3, $4, $5, $6, 'active', $7, $7)
     ON CONFLICT (user_id, slug) DO UPDATE SET chunk_count = EXCLUDED.chunk_count, status = 'active', updated_at = EXCLUDED.updated_at`,
    [userId, chunks[0]?.domain || "unknown", chunks[0]?.domain?.toLowerCase().replace(/\s+/g, "_") || "unknown", `Knowledge pack: ${chunks[0]?.domain}`, chunks[0]?.category || "general", loaded, Date.now()]
  );
  return loaded;
}

// ══════════════════════════════════════════════════════════════════════
// HAIR ART KNOWLEDGE — стрижки, окрашивания, колористика, история
// ══════════════════════════════════════════════════════════════════════

export const HAIR_ART_KNOWLEDGE: KnowledgeChunk[] = [
  // History of Hairstyling
  { domain: "Hair Art", category: "history", title: "Ancient Egypt Hair Traditions", content: "Ancient Egyptians were pioneers of hair styling. They used henna for coloring, beeswax for hold, and created elaborate wigs from human hair and sheep wool. Cleopatra popularized the geometric bob. Social status was displayed through hairstyle complexity — priests shaved heads while royalty wore ornate wigs with gold threads.", importance: 0.8, tags: ["history", "ancient", "egypt"] },
  { domain: "Hair Art", category: "history", title: "Greek and Roman Hair Culture", content: "Ancient Greeks favored natural curls enhanced with olive oil and gold dust. Roman women used iron bars (calamistrum) heated over flame — the first curling irons. Hair coloring used saffron for blonde, henna for red, and lead combs for darkening. Elaborate updos (tutulus) signified married women.", importance: 0.8, tags: ["history", "ancient", "greece", "rome"] },
  { domain: "Hair Art", category: "history", title: "Renaissance to Baroque Hair", content: "Renaissance Italy brought the high forehead trend — women plucked hairlines back. Baroque era (1600s) introduced massive powdered wigs in France under Louis XIV. Marie Antoinette's hairdresser Léonard Autié created towering 'pouf' styles 3+ feet tall with ships, birdcages, and gardens woven in.", importance: 0.8, tags: ["history", "renaissance", "baroque"] },
  { domain: "Hair Art", category: "history", title: "The 1920s Bob Revolution", content: "The 1920s bob cut was a feminist revolution. Irene Castle started the trend, Louise Brooks made it iconic. The 'Marcel Wave' (invented by François Marcel in 1872 but popularized in the 1920s) used heated tongs to create S-shaped waves. Coco Chanel cutting her hair short made it socially acceptable. Flappers paired bobs with finger waves.", importance: 0.9, tags: ["history", "1920s", "bob", "revolution"] },
  { domain: "Hair Art", category: "history", title: "Vidal Sassoon Revolution (1960s)", content: "Vidal Sassoon revolutionized hairdressing by making the cut the foundation — 'the cut IS the style.' His geometric 5-point cut (1964), the asymmetric bob, and the Nancy Kwan cut eliminated the need for rollers and hairspray. He treated hair cutting as architecture. His approach — wash and wear, precision geometry — changed the industry forever.", importance: 0.95, tags: ["history", "sassoon", "1960s", "geometric", "revolution"] },
  { domain: "Hair Art", category: "history", title: "Black Hair Culture and Civil Rights", content: "Black hair has deep cultural significance. The Afro became a political statement in the 1960s-70s (Angela Davis, Black Panthers). Madam C.J. Walker (1867-1919) was the first Black female self-made millionaire through hair care products. Cornrows carry African heritage dating back 3000+ years. The CROWN Act (2020s) fights hair discrimination. Locs, braids, twists — each style tells a story.", importance: 0.9, tags: ["history", "culture", "black-hair", "afro", "braids"] },
  { domain: "Hair Art", category: "history", title: "Japanese Hair Art Tradition", content: "Japanese hair art (kamisuki) is centuries old. Geisha hairstyles (shimada, momoware) are architectural masterpieces using bintsuke wax, combs (kushi), and decorative pins (kanzashi). Samurai topknots (chonmage) were practical and symbolic. Modern Japanese hairdressing leads global trends — the 'shag', 'wolf cut', and precision layering originated from Tokyo salons.", importance: 0.85, tags: ["history", "japanese", "geisha", "culture"] },

  // Cutting Techniques
  { domain: "Hair Art", category: "cutting", title: "Fundamental Cutting Techniques", content: "Core techniques: (1) Blunt/one-length cut — all hair same length, creates weight line; (2) Graduated cut — stacked layers, shorter at nape, creates triangle shape; (3) Layered cut — internal layers remove weight, create movement; (4) Textured/point cut — scissors held vertically to soften ends. Every complex cut combines these four foundations.", importance: 0.95, tags: ["cutting", "fundamentals", "technique"] },
  { domain: "Hair Art", category: "cutting", title: "Precision vs. Freehand Cutting", content: "Precision cutting (Sassoon school) uses exact sections, consistent elevation angles, and mathematical geometry. Freehand cutting (Toni&Guy, Bumble) relies on visual flow and intuitive shaping. Dry cutting shows the true fall of hair — curly hair MUST be cut dry. Razor cutting creates soft, wispy textures but damages some hair types. Slide cutting removes bulk without changing length.", importance: 0.9, tags: ["cutting", "precision", "freehand", "technique"] },
  { domain: "Hair Art", category: "cutting", title: "Modern Cutting Trends 2024-2026", content: "Current trends: (1) The 'Butterfly Cut' — face-framing layers that flip outward like wings; (2) 'Italian Bob' — chin-length with soft layers and curtain bangs; (3) 'Wolf Cut' — mullet meets shag, heavily layered; (4) 'Bixie' — bob meets pixie hybrid; (5) 'Octopus Cut' — heavy top layers with long tentacle-like lengths. The trend is toward low-maintenance, lived-in textures over perfectly polished looks.", importance: 0.85, tags: ["cutting", "trends", "2024", "2025", "2026"] },

  // Coloring — Theory
  { domain: "Hair Art", category: "color-theory", title: "Hair Color Level System", content: "The International Color Level System: Level 1 (black) to Level 10 (lightest blonde). Each level represents a unit of lightness. Underlying pigment changes as you lift: L1-3 = red-brown, L4-5 = red-orange, L6-7 = orange-yellow, L8-9 = yellow, L10 = pale yellow. Understanding underlying pigment is the KEY to successful color — it determines what toner/gloss to use.", importance: 0.95, tags: ["color", "theory", "levels", "fundamental"] },
  { domain: "Hair Art", category: "color-theory", title: "Color Wheel and Neutralization", content: "Complementary colors neutralize each other: orange is neutralized by blue (ash), yellow by violet (purple shampoo), red by green, and green tones (from pool/minerals) by red-based colors. This is why blue-based toners cancel brassiness on blonde, and why ash formulas are used on warm unwanted tones. The color wheel is a colorist's most important mental tool.", importance: 0.95, tags: ["color", "theory", "wheel", "neutralization"] },
  { domain: "Hair Art", category: "color-theory", title: "Developer Volumes and Timing", content: "Developer (hydrogen peroxide) volumes: 10 vol (3%) = deposit only, no lift; 20 vol (6%) = 1-2 levels lift, standard for permanent color; 30 vol (9%) = 2-3 levels lift, used with lightener; 40 vol (12%) = 3-4 levels lift, maximum. Higher volume ≠ faster — it means more lift capacity. Processing time affects deposit, not lift level. Over-processing leads to damage, not more lift.", importance: 0.95, tags: ["color", "developer", "technique", "fundamental"] },

  // Coloring — Techniques
  { domain: "Hair Art", category: "color-techniques", title: "Balayage vs. Foil Highlights", content: "Balayage (French: 'to sweep') — freehand painting on hair surface, creates soft sun-kissed gradient with no harsh lines. Foilayage combines foils with balayage painting for more lift. Traditional foil highlights create precise, even lightening. Babylights use micro-thin foils to mimic fine childhood blonde. Each technique serves different goals: balayage = natural blend, foils = dramatic contrast.", importance: 0.95, tags: ["color", "balayage", "highlights", "technique"] },
  { domain: "Hair Art", category: "color-techniques", title: "Ombre, Sombre, and Color Melt", content: "Ombre = distinct dark-to-light gradient (dramatic). Sombre = 'soft ombre' — subtle 1-2 level transition. Color melt = seamless blend of 3+ colors from root to end with no visible lines. Reverse ombre goes light to dark. Shadow root = dark root blended 1-2 inches into lighter lengths for low-maintenance grow-out. All are variations of the gradient concept.", importance: 0.9, tags: ["color", "ombre", "technique", "gradient"] },
  { domain: "Hair Art", category: "color-techniques", title: "Vivid and Fashion Colors", content: "Fashion/vivid colors (Pulp Riot, Arctic Fox, Joico, Pravana) are direct dyes — they deposit without developer. Requirements: hair MUST be pre-lightened to level 9-10 for true color payoff. Pastel shades need level 10 (platinum). Semi-permanent fades in 4-8 weeks. Maintenance: cold water, sulfate-free shampoo, color-depositing conditioners. Olaplex or bond builders essential during pre-lightening.", importance: 0.9, tags: ["color", "vivid", "fashion", "technique"] },
  { domain: "Hair Art", category: "color-techniques", title: "Color Correction", content: "Color correction is the most complex service in a salon. Common scenarios: (1) Removing box dye black (requires color remover + slow lifting over multiple sessions); (2) Fixing green/blue tones (vitamin C treatment + warm color deposit); (3) Banding (uneven lift lines — requires sectioning and targeted application); (4) Over-processed blonde (protein treatments + toning, NOT more bleach). Golden rule: underpromise, overdeliver. Some corrections take 3+ sessions.", importance: 0.9, tags: ["color", "correction", "advanced"] },

  // Treatments and Hair Science
  { domain: "Hair Art", category: "treatments", title: "Hair Structure and Bond Chemistry", content: "Hair has 3 layers: cuticle (protective scales), cortex (80% of hair — contains melanin, keratin bonds), medulla (hollow center). Three bond types: hydrogen (broken by water, reformed by heat), salt (broken by pH changes), and disulfide (strongest — broken by chemical services). Olaplex works by reconnecting broken disulfide bonds via bis-aminopropyl diglycol dimaleate. K18 repairs keratin chains differently — it's a peptide that reconnects broken keratin.", importance: 0.9, tags: ["science", "bonds", "treatments"] },
  { domain: "Hair Art", category: "treatments", title: "Keratin Treatments and Smoothing", content: "Brazilian Blowout uses formaldehyde (or alternatives) to smooth frizz by sealing cuticle — lasts 10-12 weeks. Japanese Straightening (thermal reconditioning) permanently breaks and reforms disulfide bonds — grows out, doesn't wash out. Cysteine treatments are gentler alternatives. All chemical straightening reduces curl permanently in treated sections. Important: virgin (uncolored) hair responds best; heavily processed hair risks breakage.", importance: 0.85, tags: ["treatments", "keratin", "smoothing"] },

  // Great Hairstylists
  { domain: "Hair Art", category: "legends", title: "Legendary Hairstylists", content: "Vidal Sassoon — geometric cutting revolution. Alexandre de Paris — styled Grace Kelly, Audrey Hepburn, Elizabeth Taylor. Oribe Canales — editorial genius, created 'supermodel hair' of the 90s. Sam McKnight — Princess Diana's stylist, shaped modern British cool. Guido Palau — most influential runway hairstylist alive, Redken global creative director. Jen Atkin — made hairstyling a social media empire (Ouai brand), styles Kardashians/Hadids.", importance: 0.85, tags: ["legends", "stylists", "history"] },
  { domain: "Hair Art", category: "legends", title: "Innovators in Black Hair Care", content: "Madam C.J. Walker — first self-made female millionaire, hair care empire for Black women. Annie Turnbo Malone — actually preceded Walker, created the Poro method. Lisa Price — founded Carol's Daughter from her Brooklyn kitchen. Richelieu Dennis — founded SheaMoisture, revived African beauty traditions. Miss Jessie's (Miko and Titi Branch) — pioneered the natural curls movement in NYC. Vernon François — celebrity stylist pushing diversity in editorial hair.", importance: 0.85, tags: ["legends", "black-hair", "innovators"] },

  // Business & Industry
  { domain: "Hair Art", category: "industry", title: "Salon Business Models 2024-2026", content: "Current models: (1) Commission salon — stylist gets 40-60% of service; (2) Booth rental — stylist pays fixed rent ($200-500/week), keeps all revenue; (3) Suite rental (Sola, My Salon Suite) — independent operation; (4) Mobile/home salon — lowest overhead, growing post-COVID; (5) Subscription model — monthly membership for unlimited blowouts (Drybar, Primp & Blow). Trend: independence. 60%+ of stylists under 35 prefer rental/suite models.", importance: 0.8, tags: ["business", "salon", "industry", "trends"] },
];

// ══════════════════════════════════════════════════════════════════════
// ART HISTORY KNOWLEDGE
// ══════════════════════════════════════════════════════════════════════

export const ART_KNOWLEDGE: KnowledgeChunk[] = [
  { domain: "Art History", category: "movements", title: "Renaissance (1400-1600)", content: "Rebirth of classical Greek/Roman ideals. Linear perspective (Brunelleschi), anatomical accuracy, humanism. Key artists: Leonardo da Vinci (Mona Lisa, Last Supper), Michelangelo (Sistine Chapel, David), Raphael (School of Athens). Moved art from flat religious icons to naturalistic 3D space. Oil painting technique perfected by Northern Renaissance (Jan van Eyck). Patronage system — Medici family funded most of Florence's art.", importance: 0.9, tags: ["art", "renaissance", "history"] },
  { domain: "Art History", category: "movements", title: "Impressionism (1860s-1880s)", content: "Rejected academic rules — painted outdoors (en plein air), captured light and movement. Claude Monet (Water Lilies, Impression Sunrise — gave the movement its name), Pierre-Auguste Renoir, Edgar Degas, Berthe Morisot (one of few female Impressionists recognized in her time). Used visible brushstrokes, pure color, everyday subjects. First exhibited at Salon des Refusés 1874 after being rejected by official Salon.", importance: 0.9, tags: ["art", "impressionism", "history"] },
  { domain: "Art History", category: "movements", title: "Post-Impressionism to Expressionism", content: "Post-Impressionism: Cézanne (father of modern art — geometric forms), Van Gogh (emotional color, Starry Night), Gauguin (primitivism, Tahiti). Fauvism: Matisse — wild color, flat forms. Expressionism: Munch (The Scream), Kirchner — distorted reality to show inner emotion. Die Brücke and Der Blaue Reiter groups. Each movement pushed further from representation toward emotion and abstraction.", importance: 0.85, tags: ["art", "post-impressionism", "expressionism"] },
  { domain: "Art History", category: "movements", title: "Cubism and Abstract Art", content: "Cubism (1907-): Picasso and Braque shattered perspective — showed multiple viewpoints simultaneously. Les Demoiselles d'Avignon (1907) broke everything. Analytical Cubism (monochrome, fragmented), Synthetic Cubism (collage, color). Led directly to Abstract art: Kandinsky (first pure abstraction, 1910), Mondrian (De Stijl — primary colors + grid), Malevich (Suprematism — Black Square). Art freed from representing reality.", importance: 0.9, tags: ["art", "cubism", "abstract", "history"] },
  { domain: "Art History", category: "movements", title: "Surrealism and Dada", content: "Dada (1916, Zurich) — anti-art response to WWI's absurdity. Duchamp's Fountain (urinal signed 'R. Mutt') questioned what art IS. Surrealism (1924, André Breton manifesto): accessing the unconscious mind. Salvador Dalí (melting clocks, Persistence of Memory), René Magritte (Treachery of Images — 'This is not a pipe'), Frida Kahlo (personal surrealism rooted in pain and identity), Max Ernst (frottage, grattage techniques).", importance: 0.85, tags: ["art", "surrealism", "dada", "history"] },
  { domain: "Art History", category: "movements", title: "Pop Art and Contemporary", content: "Pop Art (1950s-60s): Andy Warhol (Campbell's Soup, Marilyn), Roy Lichtenstein (comic dots), Jasper Johns (flags). Made commercial culture into fine art. Street Art: Banksy (anonymous, political), Jean-Michel Basquiat (neo-expressionism from graffiti), Keith Haring (public art, activism). Contemporary: Damien Hirst (shock art, diamond skull), Jeff Koons (kitsch), Yayoi Kusama (infinity rooms), Ai Weiwei (political).", importance: 0.85, tags: ["art", "pop-art", "contemporary", "street-art"] },
  { domain: "Art History", category: "movements", title: "Digital Art and AI Art (2020s)", content: "NFT explosion (2021) — Beeple's 'Everydays' sold for $69M at Christie's. Refik Anadol — data sculptures and immersive AI installations (MoMA 'Unsupervised'). DALL-E, Midjourney, Stable Diffusion democratized image creation (2022+). Debate: is AI art real art? Artists like Holly Herndon and Mat Dryhurst argue for 'co-creation.' Digital art institutions: teamLab (Tokyo), SuperRare, Art Blocks. The question is no longer 'can machines create art' but 'what does human creativity mean now.'", importance: 0.85, tags: ["art", "digital", "AI", "NFT", "contemporary"] },
];

// ══════════════════════════════════════════════════════════════════════
// MUSIC HISTORY KNOWLEDGE
// ══════════════════════════════════════════════════════════════════════

export const MUSIC_KNOWLEDGE: KnowledgeChunk[] = [
  { domain: "Music History", category: "classical", title: "Classical Music Eras", content: "Baroque (1600-1750): Bach, Vivaldi, Handel — polyphony, ornamentation, harpsichord. Classical (1750-1820): Mozart, Beethoven, Haydn — clarity, balance, symphony form. Romantic (1820-1900): Chopin, Liszt, Wagner, Tchaikovsky — emotion, virtuosity, program music. 20th Century: Stravinsky (Rite of Spring caused a riot, 1913), Schoenberg (12-tone serialism), Debussy (impressionist harmony). Each era rebelled against the previous.", importance: 0.9, tags: ["music", "classical", "history"] },
  { domain: "Music History", category: "jazz-blues", title: "Blues, Jazz, and Their Legacy", content: "Blues: born in Mississippi Delta (1890s), field hollers + African rhythms. Robert Johnson, B.B. King, Muddy Waters. The 12-bar blues progression is the DNA of rock, R&B, and hip-hop. Jazz: New Orleans 1900s, improvisation as core. Louis Armstrong, Duke Ellington, Charlie Parker (bebop revolution), Miles Davis (reinvented jazz 5 times — cool jazz, modal, fusion), John Coltrane (spiritual jazz). Jazz is the only truly American art form.", importance: 0.9, tags: ["music", "jazz", "blues", "history"] },
  { domain: "Music History", category: "rock-pop", title: "Rock and Pop Evolution", content: "1950s: Chuck Berry, Little Richard, Elvis — rock'n'roll from blues+country. 1960s: Beatles (pop revolution), Rolling Stones (blues-rock), Hendrix (guitar as weapon), Motown (Supremes, Stevie Wonder). 1970s: Led Zeppelin, Pink Floyd (concept albums), punk (Ramones, Sex Pistols — DIY rebellion), disco. 1980s: MTV changed everything — Michael Jackson (Thriller), Madonna, Prince, synth-pop. 1990s: grunge (Nirvana — killed hair metal), hip-hop became dominant.", importance: 0.9, tags: ["music", "rock", "pop", "history"] },
  { domain: "Music History", category: "hip-hop", title: "Hip-Hop: From Bronx to Global", content: "Born August 11, 1973 — DJ Kool Herc's party in the Bronx. Four pillars: DJing, MCing, breakdancing, graffiti. Grandmaster Flash, Run-DMC, LL Cool J (1980s). Golden Age (late 80s-90s): Public Enemy, NWA, Tupac, Biggie, Wu-Tang Clan, Nas (Illmatic = greatest hip-hop album debate). 2000s: Kanye West redefined production aesthetics. 2010s-20s: Drake, Kendrick Lamar, Travis Scott. Hip-hop surpassed rock as world's most popular genre in 2017.", importance: 0.9, tags: ["music", "hip-hop", "history", "culture"] },
  { domain: "Music History", category: "electronic", title: "Electronic Music Evolution", content: "Kraftwerk (1970s Germany) — founded electronic music. Synth-pop (Depeche Mode, New Order). House music (Chicago, 1980s — Frankie Knuckles = 'Godfather of House'). Techno (Detroit — Juan Atkins, Derrick May, Kevin Saunderson). 1990s: rave culture, UK jungle/drum'n'bass, trance. 2010s: EDM mainstream (Skrillex, Deadmau5, Calvin Harris). Current: hyperpop, ambient resurgence, AI-generated music. Berlin remains the global capital of electronic music.", importance: 0.85, tags: ["music", "electronic", "house", "techno"] },
  { domain: "Music History", category: "global", title: "Global Music Influences", content: "Latin: bossa nova (Brazil, 1950s), reggaeton (Puerto Rico, 2000s — now global via Bad Bunny, J Balvin). K-pop: BTS, BLACKPINK — industrial-scale production meets fandom culture. Afrobeats: Burna Boy, Wizkid — Nigeria's global sound. Reggae: Bob Marley made Jamaica's music universal. Indian film music (Bollywood) is the world's largest music industry by volume. Fado (Portugal), Flamenco (Spain), Amapiano (South Africa) — each region has its signature sound.", importance: 0.85, tags: ["music", "global", "culture"] },
];

// ══════════════════════════════════════════════════════════════════════
// FASHION HISTORY KNOWLEDGE
// ══════════════════════════════════════════════════════════════════════

export const FASHION_KNOWLEDGE: KnowledgeChunk[] = [
  { domain: "Fashion History", category: "designers", title: "Founding Designers", content: "Charles Frederick Worth (1825-1895) — invented haute couture, first to put labels in clothing. Coco Chanel — liberated women from corsets, created the little black dress (1926), Chanel No.5, tweed suits. She said 'fashion fades, only style remains.' Christian Dior — 'New Look' (1947) with cinched waists and full skirts restored femininity post-war. Cristóbal Balenciaga — Chanel called him 'the only real couturier,' master of architectural construction.", importance: 0.9, tags: ["fashion", "designers", "history", "couture"] },
  { domain: "Fashion History", category: "designers", title: "Revolutionary Designers", content: "Yves Saint Laurent — Le Smoking tuxedo for women (1966), democratized fashion with ready-to-wear. Alexander McQueen — fashion as theater and provocation, 'Savage Beauty' exhibition. Vivienne Westwood — punk fashion inventor, brought subculture to runway. Rei Kawakubo (Comme des Garçons) — destroyed Western beauty standards with asymmetry and deconstruction. Virgil Abloh — first Black artistic director at Louis Vuitton, bridged streetwear and luxury.", importance: 0.9, tags: ["fashion", "designers", "revolution"] },
  { domain: "Fashion History", category: "decades", title: "Fashion by Decade", content: "1920s: flapper dresses, dropped waists, liberation. 1950s: Dior's New Look, poodle skirts, Elvis influence. 1960s: mini skirt (Mary Quant), mod culture, Twiggy. 1970s: disco glam, punk safety pins, hippie bohemia. 1980s: power shoulders, neon, Madonna. 1990s: grunge flannel, minimalism (Calvin Klein), supermodels (Naomi, Cindy, Linda). 2000s: low-rise everything, logomania. 2010s: athleisure, Instagram fashion. 2020s: quiet luxury, sustainability, gender-fluid dressing.", importance: 0.9, tags: ["fashion", "decades", "history", "trends"] },
  { domain: "Fashion History", category: "culture", title: "Streetwear and Fashion Democracy", content: "Streetwear started with Shawn Stussy (1980s surfwear) and grew through Supreme (1994, NYC skate culture), A Bathing Ape (Nigo, Tokyo). The Supreme x Louis Vuitton collab (2017) officially merged street and luxury. Off-White (Virgil Abloh) used quotation marks and industrial tape as design language. Fear of God (Jerry Lorenzo), Yeezy (Kanye West) — celebrity-designer era. Sneaker culture: Nike Air Jordan (1985) created the $100B+ resale market. Streetwear democratized fashion — you don't need couture to have style.", importance: 0.85, tags: ["fashion", "streetwear", "culture", "sneakers"] },
  { domain: "Fashion History", category: "sustainability", title: "Sustainable Fashion Movement", content: "Fast fashion (Zara, H&M, Shein) produces 100B+ garments/year — fashion is 2nd most polluting industry. The Rana Plaza collapse (2013, Bangladesh, 1,134 deaths) was a turning point. Stella McCartney pioneered luxury sustainability. Patagonia — 'Don't Buy This Jacket' campaign. Circular fashion: The RealReal, Vestiaire Collective, Depop. Gen-Z drives the shift: 73% willing to pay more for sustainable brands. Upcycling, deadstock fabric, digital fashion (DressX) are current solutions.", importance: 0.85, tags: ["fashion", "sustainability", "ethics"] },
  { domain: "Fashion History", category: "connection", title: "Fashion-Hair-Music Connection", content: "Fashion, hair, and music are inseparable: punk (Vivienne Westwood + mohawks + Sex Pistols), hip-hop (Dapper Dan + fades + Run-DMC), grunge (flannel + unwashed hair + Nirvana), K-pop (coordinated styling + dyed hair + BTS). David Bowie (Ziggy Stardust) merged all three into one artistic statement. Lady Gaga continued this tradition. The red carpet / runway / music video triangle drives global trends. Stylists who understand all three domains are the most valuable in the industry.", importance: 0.9, tags: ["fashion", "music", "hair", "culture", "connection"] },
];
